{{- define "hlib.externalSecrets.tpl" -}}
{{- $ := .context -}}
{{- $es := .values | default $.Values.externalSecrets -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "hlib.util.tplrender" (dict "value" ($es.name | default (include "hlib.fullname" $)) "context" $) }}
  labels: {{- include "hlib.labels" $ | nindent 4 }}
  {{- if $es.annotations }}
  annotations: {{- include "hlib.util.tplrender" (dict "value" $es.annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  {{- if $es.refreshPolicy }}
  refreshPolicy: {{ include "hlib.util.tplrender" (dict "value" $es.refreshPolicy "context" $) }}
  {{- end }}
  {{- if $es.refreshInterval }}
  refreshInterval: {{ include "hlib.util.tplrender" (dict "value" $es.refreshInterval "context" $) }}
  {{- end }}
  {{- if $es.syncWindows }}
  syncWindows: {{- include "hlib.util.tplrender" (dict "value" $es.syncWindows "context" $) | nindent 4 }}
  {{- end }}
  {{- if $es.secretStoreRef }}
  secretStoreRef:
    {{- if $es.secretStoreRef.name }}
    name: {{ include "hlib.util.tplrender" (dict "value" $es.secretStoreRef.name "context" $) }}
    {{- end }}
    {{- if $es.secretStoreRef.kind }}
    kind: {{ include "hlib.util.tplrender" (dict "value" $es.secretStoreRef.kind "context" $) }}
    {{- end }}
  {{- end }}
  {{- if $es.target }}
  target:
    {{- if $es.target.name }}
    name: {{ include "hlib.util.tplrender" (dict "value" $es.target.name "context" $) }}
    {{- end }}
    {{- if $es.target.creationPolicy }}
    creationPolicy: {{ include "hlib.util.tplrender" (dict "value" $es.target.creationPolicy "context" $) }}
    {{- end }}
    {{- if $es.target.deletionPolicy }}
    deletionPolicy: {{ include "hlib.util.tplrender" (dict "value" $es.target.deletionPolicy "context" $) }}
    {{- end }}
    {{- if hasKey $es.target "immutable" }}
    immutable: {{ include "hlib.util.tplrender" (dict "value" $es.target.immutable "context" $) }}
    {{- end }}
    {{- if $es.target.template }}
    template: {{- include "hlib.util.tplrender" (dict "value" $es.target.template "context" $) | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- if $es.data }}
  data: {{- include "hlib.util.tplrender" (dict "value" $es.data "context" $) | nindent 4 }}
  {{- end }}
  {{- if $es.dataFrom }}
  dataFrom: {{- include "hlib.util.tplrender" (dict "value" $es.dataFrom "context" $) | nindent 4 }}
  {{- end }}
{{- end }}

{{- define "hlib.externalSecrets" -}}
{{- if .override }}
{{- $_ := set . "base" "hlib.externalSecrets.tpl" -}}
{{- include "hlib.util.merge" . -}}
{{- else }}
{{- toYaml (fromYaml (include "hlib.externalSecrets.tpl" .)) -}}
{{- end -}}
{{- end -}}
